<!--
 * @Author: your name
 * @Date: 2021-05-26 16:50:01
 * @LastEditTime: 2021-05-26 17:29:44
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /my-docs/docs/60234702.md
-->

## 记录

[阮一峰老师写的就很详细了](https://es6.ruanyifeng.com/#docs/generator)

## 理解

### 1

调用 `Generator` 函数，返回一个遍历器对象，代表 `Generator` 函数的内部指针。

以后，每次调用遍历器对象的 `next` 方法，就会返回一个有着 `value` 和 `done` 两个属性的对象。

`value` 属性表示当前的 **内部状态的值**，是 `yield` 表达式后面那个表达式的值；`done` 属性是一个 **布尔值**，表示 **是否遍历结束**。

### 2

`next` / `throw` / `return` 三个方法都是让 `generator` 恢复执行，效果上的不同在于，`it.next( value )` 是将 `generator` 里面的 `yield` 表达式 **替换** 为  一个值。

`it.throw( value )`是将 `yield` 表达式替换为一个 `throw` 语句，`it.return( value )`是将 `yield` 表达式替换为一个 `return` 语句。

基于这个理解，`generator` 内部的各种 `return` / `throw` 行为就按一般情况来预期。如果 `return` / `throw` 出现在 `try` 内，那么有捕获就捕获，有 `finally` 就执行 `finally`；

如果最后 `return` / `throw` 到了函数外部，那么这个 `generator` 自然就变成 `complete` 状态，而外部 `caller` 自然就应该收到返回值或抛出异常。
